export default {
  programmingLanguagesTools: [
    'Java',
    'Javascript',
    'Python',
    'React',
    'Redux',
    'Swift',
    'GIT',
    'Html5',
    'Css3',
    'Unit Test',
    'C',
    'C++',
    'MySQL',
    'iOS development',
    'Android',
    'Objective-c',
    'Machine Learning',
  ],
  workflow: [
    'TDD',
    'Mobile-First',
    'Responsive Design',
    'Agile Development',
    'Scrum',
  ],
};
